#!/bin/bash
set -euo pipefail

[[ "$(whoami)" == 'messengers_perf' ]] || exit 1

# TMPDIR cleanup
find  /tmp -maxdepth 1 -type d  -name '*messengers*' -not -newermt "$(date --date='2 hour ago' '+%F')" | xargs --no-run-if-empty rm -r
# extraction dir cleanup
# to be run in the dir with subdirs with extracted data
find * -maxdepth 2 -type f -name '*.gz'  -size 20c  -not -newermt "$(date --date='2 hour ago' '+%F')" | xargs --no-run-if-empty rm
find * -maxdepth 1 -type d -name '1*'    -empty     -not -newermt "$(date --date='2 hour ago' '+%F')" | xargs --no-run-if-empty rmdir
