{
 "title": "Messengers performance",
 "time": { "from": "2023-10-03T15:00:00.000Z", "to": "2023-10-17T19:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": "select distinct run_id from power_hourly"
   },
   {
    "name": "app_id",
    "label": "App",
    "query": "select distinct app_id from power_hourly"
   }
  ]
 },
 "panels": [
  {
   "title": "Narration",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "This is a very limited study of resource usage by messaging apps on Android.\nIt needs more apps, devices and picky readers and reviewers.\n\n# Conclusions\n\nConversations (XMPP) seems best for battery life, traffic and RAM.\n\nFacebook Messenger and Element (Matrix) are the worst from the studied apps, draining up to 300x more power than Conversations when battery optimization is disabled.\n\nElement X (experimental Matrix app) is coming up with a more than 100x reduction in energy consumption (comparing to Element), drawing just 2x more power than Conversations.\n\nA few more proprietary messengers have been measured and they fall in between the space between the above mentioned extremes. Little can be said about them besides that most of them continuously draw substantial amount of power and bandwidth even when not interacted with."
   }
  },
  {
   "title": "Greetings from author",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<table border=0>\n<tr>\n<td>\nHi, I'm <a href=\"https://autkin.net\">Andriy Utkin</a>.\n\nI run an XMPP server at <a href=\"https://decent.im\">decent.im</a>.\n\nI made this research to find out the facts, not to prove any beliefs or prop up attractiveness of any chat network.\n\nI hope you enjoy reading this and it proves to be a useful knowledge for you.\n\n\nYou can:\n* [Add your data](https://github.com/decent-im/messengers-perf)\n* [Donate](https://nurture.decent.im/) (mention `messengers-perf` in the comment)\n* [Ask, thank or tell me something](mailto:messengers-perf@autkin.net)\n\n</td>\n<td>\n<img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/510px-Flag_of_Ukraine.svg.png\">\n</td>\n</tr>\n</table>"
   }
  },
  {
   "title": "Median measurements per app",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH\napps (app_id) AS (\n\tSELECT DISTINCT app_id FROM power_hourly\n),\ncool_view AS (\n    SELECT\n\tapp_id,\n    (\n        SELECT PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY rate)\n        FROM power_hourly\n        WHERE power_hourly.app_id = apps.app_id\n    ) AS median_power,\n\t(\n        SELECT PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY bandwidth)\n        FROM bandwidth_hourly\n        WHERE bandwidth_hourly.app_id = apps.app_id\n    ) AS median_bandwidth,\n\t(\n        SELECT PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY ram_use)\n        FROM app_readings\n        WHERE app_readings.app_id = apps.app_id\n        AND \"timestamp\" > '2023-10-03 16:00:00'\n    ) AS median_ram\n    FROM apps\n)\n\nSELECT app_id,\nROUND(median_power) AS \"Power draw, uW\",\nROUND(median_bandwidth) AS \"Bandwidth, B/s\",\nROUND(median_ram/1024.0/1024) AS \"RAM, MB\"\nFROM cool_view\nORDER BY \"median_power\""
    }
   ]
  },
  {
   "title": "Median measurements per device and app",
   "type": "table",
   "gridPos": { "h": 28, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH\napp_runs (app_run, run_id, app_id) AS (\n\tSELECT DISTINCT app_run, run_id, app_id FROM power_hourly\n    -- WHERE run_id in ($device) AND app_id in ($app_id) -- public dashboard = no vars\n),\ncool_view AS (\n    SELECT\n    run_id,\n    app_id,\n    (\n        SELECT PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY rate)\n        FROM power_hourly\n        WHERE power_hourly.run_id = app_runs.run_id AND power_hourly.app_id = app_runs.app_id\n    ) AS median_power,\n\t(\n        SELECT PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY bandwidth)\n        FROM bandwidth_hourly\n        WHERE bandwidth_hourly.run_id = app_runs.run_id AND bandwidth_hourly.app_id = app_runs.app_id\n    ) AS median_bandwidth,\n\t(\n        SELECT PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY ram_use)\n        FROM app_readings\n        WHERE app_readings.run_id = app_runs.run_id\n        AND app_readings.app_id = app_runs.app_id\n        AND \"timestamp\" > '2023-10-03 16:00:00'\n    ) AS median_ram\n    FROM app_runs\n)\n\nSELECT run_id  AS \"Device\", app_id,\nROUND(median_power::numeric, 1) AS \"Power draw, uW\",\nROUND(median_bandwidth::numeric, 1) AS \"Bandwidth, B/s\",\nROUND(median_ram/1024.0/1024) AS \"RAM, MB\"\nFROM cool_view\nORDER BY \"Device\", median_power"
    }
   ]
  },
  {
   "title": "Narration",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "options": {
    "content": "# What is behind these stats?\n\nI used 5 different Android devices available to me to collect this data.\n\nSome of them are in active daily manual use, some are doubles of daily-used ones, some sit doing nothing but letting these apps work in a synthetic setup.\n\n# Devices\n\n## 1\n\nLenovo K10a40 (2016), Android 6.0.\n\nI have put on it Conversations, Element and Facebook Messenger.\nConversations and Element ask to disable battery optimization, so I did it for all three apps.\nIt's this phone which demonstrates huge energy draw by the apps.\n\nAll these messengers I have populated with one idle contact.\nElement also tracks 2 chatrooms.\nConversations tracks 1 chatroom.\n\nThe phone runs no other workload and sits on the shelf.\n\n## 2\n\nLenovo K520 (2018), Android 8.0.\n\nDaily driver phone, K-9 and Conversations are actively used. Conversation app is exempt from battery optimization.\n\nData stops on Oct 5 as USB port started to reliably fail to establish data connection, so I couldn't ADB it anymore.\n\n## 3\n\nPixel 7 (2022), Android 13.\n\nDaily driver phone. Telegram, GMail, K-9, Conversations are actively used.\n\nViber, Whatsapp, Twitter and Facebook Messenger are completely unused, yet they draw non-trivial amounts of power and traffic.\nFor example, unused Twitter draws 3x more power than daily used Conversations.\nFB Messenger draws slightly more than Twitter; Viber 7x Twitter; Whatsapp 25x Twitter.\n\nTelegram eats a lot.\nWithout further data, this could be judged as fair, as it's more actively used.\nStill, on this phone it eats 400x more power than Conversations, and 23x more power than GMail.\n\nAll apps have battery optimization in place.\n\n## 4\n\nMoto C Plus (2017), Android 7.0.\n\nSits on the shelf, but has messenger accounts enabled.\n\nOnly Conversations and Viber have battery optimization disabled.\n\n## 5\n\nLenovo K520 (2018), Android 8.0.\n\nSits on the shelf, but has messenger accounts enabled.\n\nConversations and Telegram have battery optimization disabled.\n\nInteresting how power-restricted Viber draws 5x more than non-restricted Telegram.\n\n# App ID hints\n\n* eu.siacs.conversations is XMPP app <a href=\"https://conversations.im\">Conversations</a>.\n* im.vector.app is Matrix app <a href=\"https://matrix.org/ecosystem/clients/element/\">Element</a>.\n* io.element.android.x is Matrix experimental app <a href=\"https://element.io/labs/element-x\">Element X</a>.\n* com.google.android.gm is GMail app.\n* com.facebook.orca is Facebook Messenger.\n"
   }
  },
  {
   "title": "Narration",
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "options": {
    "content": "# Let's see more\n\nLet's calculate not just the median, but percentiles of the power draw, the bandwidth used, and RAM footprint.\n\nI want to plot the percentile as the horisontal axis.\nBut Grafana wants to do time series, so I will pretend that the percentiles are times.\nI will plot 11 points, at 0%, 10%, ..., 90%, 100%.\nThe point in the middle is 50% (median).\n\nThe differences in the numbers plotted are huge, so we will use log-scale vertical axis."
   }
  },
  {
   "title": "Power exceedance curves (uW)",
   "type": "timeseries",
   "description": "Y-axis is power, log-scale. X-axis is frequency, 0% - 100%. Middle point of the chart is median, 50% of observations have higher power, 50% have lower power than the value plotted. Every point is 10-percent increment.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "WITH\npercentiles_to_present (percentile) AS (\n    VALUES (0.0), (0.1), (0.2), (0.3), (0.4), (0.5), (0.6), (0.7), (0.8), (0.9), (1.0)\n),\nruns_to_plot (app_run) AS (\n\tSELECT DISTINCT app_run FROM power_hourly\n    -- WHERE run_id in ($device) AND app_id in ($app_id)\n),\ncool_view AS (\n    SELECT\n    -- $__from + percentile * ($__to - $__from) AS percentile_as_time, -- fails in public dashboard\n    '2023-10-03 16:00'::timestamptz + percentile * ('2023-10-17 20:00'::timestamptz - '2023-10-03 16:00'::timestamptz) AS percentile_as_time,\n    app_run,\n    (\n        SELECT PERCENTILE_CONT(percentile) WITHIN GROUP(ORDER BY rate)\n        FROM power_hourly\n        WHERE power_hourly.app_run = runs_to_plot.app_run\n    ) AS power_exceedance\n    FROM percentiles_to_present CROSS JOIN runs_to_plot\n)\n\nSELECT\npercentile_as_time AS time, app_run, power_exceedance\nFROM cool_view\nORDER BY \"time\", app_run"
    }
   ]
  },
  {
   "title": "Power exceedance curves (uW), linear scale",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "WITH\npercentiles_to_present (percentile) AS (\n    VALUES (0.0), (0.1), (0.2), (0.3), (0.4), (0.5), (0.6), (0.7), (0.8), (0.9), (1.0)\n),\nruns_to_plot (app_run) AS (\n\tSELECT DISTINCT app_run FROM power_hourly\n    -- WHERE run_id in ($device) AND app_id in ($app_id)\n),\ncool_view AS (\n    SELECT\n    -- $__from + percentile * ($__to - $__from) AS percentile_as_time, -- fails in public dashboard\n    '2023-10-03 16:00'::timestamptz + percentile * ('2023-10-17 20:00'::timestamptz - '2023-10-03 16:00'::timestamptz) AS percentile_as_time,\n    app_run,\n    (\n        SELECT PERCENTILE_CONT(percentile) WITHIN GROUP(ORDER BY rate)\n        FROM power_hourly\n        WHERE power_hourly.app_run = runs_to_plot.app_run\n    ) AS power_exceedance\n    FROM percentiles_to_present CROSS JOIN runs_to_plot\n)\n\nSELECT\npercentile_as_time AS time, app_run, power_exceedance\nFROM cool_view\nORDER BY \"time\", app_run"
    }
   ]
  },
  {
   "title": "Power exceedance curves (uW), linear scale, zoom into low consumption league",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "rawSql": "WITH\npercentiles_to_present (percentile) AS (\n    VALUES (0.0), (0.1), (0.2), (0.3), (0.4), (0.5), (0.6), (0.7), (0.8), (0.9), (1.0)\n),\nruns_to_plot (app_run) AS (\n\tSELECT DISTINCT app_run FROM power_hourly\n    -- WHERE run_id in ($device) AND app_id in ($app_id)\n),\ncool_view AS (\n    SELECT\n    -- $__from + percentile * ($__to - $__from) AS percentile_as_time, -- fails in public dashboard\n    '2023-10-03 16:00'::timestamptz + percentile * ('2023-10-17 20:00'::timestamptz - '2023-10-03 16:00'::timestamptz) AS percentile_as_time,\n    app_run,\n    (\n        SELECT PERCENTILE_CONT(percentile) WITHIN GROUP(ORDER BY rate)\n        FROM power_hourly\n        WHERE power_hourly.app_run = runs_to_plot.app_run\n    ) AS power_exceedance\n    FROM percentiles_to_present CROSS JOIN runs_to_plot\n)\n\nSELECT\npercentile_as_time AS time, app_run, power_exceedance\nFROM cool_view\nORDER BY \"time\", app_run"
    }
   ]
  },
  {
   "title": "Bandwidth exceedance curves (B/s)",
   "type": "timeseries",
   "description": "Y-axis is bandwidth, log-scale. X-axis is frequency, 0% - 100%. Middle point of the chart is median, 50% of observations have higher power, 50% have lower bandwidth than the value plotted. Every point is 10-percent increment.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "rawSql": "WITH\npercentiles_to_present (percentile) AS (\n    VALUES (0.0), (0.1), (0.2), (0.3), (0.4), (0.5), (0.6), (0.7), (0.8), (0.9), (1.0)\n),\nruns_to_plot (app_run) AS (\n\tSELECT DISTINCT app_run FROM bandwidth_hourly\n    -- WHERE run_id in ($device) AND app_id in ($app_id)\n),\ncool_view AS (\n    SELECT\n    -- $__from + percentile * ($__to - $__from) AS percentile_as_time,\n    '2023-10-03 16:00'::timestamptz + percentile * ('2023-10-17 20:00'::timestamptz - '2023-10-03 16:00'::timestamptz) AS percentile_as_time,\n    app_run,\n    (\n        SELECT PERCENTILE_CONT(percentile) WITHIN GROUP(ORDER BY bandwidth)\n        FROM bandwidth_hourly\n        WHERE bandwidth_hourly.app_run = runs_to_plot.app_run\n    ) AS bandwidth_exceedance\n    FROM percentiles_to_present CROSS JOIN runs_to_plot\n)\n\nSELECT\npercentile_as_time AS time, app_run, bandwidth_exceedance\nFROM cool_view\nORDER BY \"time\", app_run"
    }
   ]
  },
  {
   "title": "RAM exceedance curves (MB)",
   "type": "timeseries",
   "description": "Y-axis is RAM use, log-scale. X-axis is frequency, 0% - 100%. Middle point of the chart is median, 50% of observations have higher power, 50% have lower RAM usage than the value plotted. Every point is 10-percent increment.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {
     "rawSql": "WITH\npercentiles_to_present (percentile) AS (\n    VALUES (0.0), (0.1), (0.2), (0.3), (0.4), (0.5), (0.6), (0.7), (0.8), (0.9), (1.0)\n),\nruns_to_plot (app_run, run_id, app_id) AS (\n\tSELECT DISTINCT app_run, run_id, app_id FROM power_hourly\n    -- WHERE run_id in ($device) AND app_id in ($app_id)\n),\ncool_view AS (\n    SELECT\n    -- $__from + percentile * ($__to - $__from) AS percentile_as_time,\n    '2023-10-03 16:00'::timestamptz + percentile * ('2023-10-17 20:00'::timestamptz - '2023-10-03 16:00'::timestamptz) AS percentile_as_time,\n\tapp_run,\n    (\n        SELECT PERCENTILE_CONT(percentile) WITHIN GROUP(ORDER BY ram_use)\n        FROM app_readings\n        WHERE\n        --(app_readings.run_id || ' ' || app_readings.app_id)  = runs_to_plot.app_run\n        \"timestamp\" > '2023-10-03 16:00:00'\n        AND app_readings.run_id = runs_to_plot.run_id\n        AND app_readings.app_id = runs_to_plot.app_id\n    ) AS ram_exceedance\n    FROM percentiles_to_present CROSS JOIN runs_to_plot\n)\n\nSELECT\npercentile_as_time AS time, app_run, ram_exceedance / 1024.0/1024 AS ram_exceedance\nFROM cool_view\nORDER BY \"time\", app_run"
    }
   ]
  },
  {
   "title": "Narration",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 101 },
   "options": {
    "content": "# Speed\n\nLet's go down another level.\nWe'll derive the speed (the rate of change) from the raw data (which you'll find at the bottom of this dashboard).\nBelow are  power draw and bandwidth use calculated in hourly intervals."
   }
  },
  {
   "title": "Power draw (uW)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {
     "rawSql": "SELECT time, app_run, rate FROM power_hourly\nWHERE\n  $__timeFilter(time)\n  -- AND run_id in ($device) AND app_id in ($app_id)"
    }
   ]
  },
  {
   "title": "Bandwidth use (B/s)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 119 },
   "targets": [
    {
     "rawSql": "SELECT time, app_run, bandwidth FROM bandwidth_hourly\nWHERE\n  $__timeFilter(time)\n  -- AND run_id in ($device) AND app_id in ($app_id)"
    }
   ]
  },
  {
   "title": "Narration",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 134 },
   "options": {
    "content": "# Raw data\n\nThree panels below are the plots of counters reported by Android itself.\nWe can see the values of attributed energy use and wifi traffic climb up, and being reset at some points.\nRAM measurements are scattered points, as the resident set size (RSS) values change over time.\n\nEach combination of device and app is plotted separately here."
   }
  },
  {
   "title": "Cumulative power use by app (mAh)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 140 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(\"timestamp\"),\n  run_id::text || ' ' || app_id,\n  energy_use\nFROM\n  app_readings\nWHERE\n  $__timeFilter(\"timestamp\")\n  -- AND run_id in ($device) AND app_id in ($app_id)\nORDER BY \"timestamp\", run_id\n"
    }
   ]
  },
  {
   "title": "Wifi data",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(\"timestamp\"),\n  run_id::text || ' ' || app_id,\n  wifi_send + wifi_recv AS wifi_data\nFROM\n  app_readings\nWHERE\n  $__timeFilter(\"timestamp\")\n  -- AND run_id in ($device) AND app_id in ($app_id)  -- no vars in public dashboard\nORDER BY \"timestamp\", run_id::text || ' ' || app_id"
    }
   ]
  },
  {
   "title": "RAM use by app",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(\"timestamp\"),\n  run_id::text || ' ' || app_id,\n  ram_use\nFROM\n  app_readings\nWHERE\n  $__timeFilter(\"timestamp\")\n  -- AND run_id in ($device) AND app_id in ($app_id) -- no vars in public dashboard\nORDER BY \"timestamp\", run_id::text || ' ' || app_id"
    }
   ]
  },
  {
   "title": "Narration",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 180 },
   "options": {
    "content": "# How is the data extracted?\n\nThe measurements come from universal Android tools invoked via `adb shell` once a minute.\nRAM use is RSS obtained from `ps`.\nBattery and wifi use come from `dumpsys batterystats`.\nThe latter report gives up to date data only when the device is not charging, so ADB connection has to be changed to TCP mode with `adb tcpip`, and the USB cable must not be plugged, except for periodical charging."
   }
  }
 ]
}